### ISSUE TITLE
Control the speed of scroll

### ISSUE THREAD

**Issue by ziyafenn** [mauricevancooten/react-anchor-link-smooth-scroll#1]
Hi there! Thanks for the easy to use package!

Would be cool when i'd be able to control the speed of scroll. Because right now i find it bit to fast :)

Thanks!

**Comment by mauricevancooten** [comment]
Hi, thanks for the feedback. That would be cool, but this package is based on the window.scroll native support from browsers with a polyfill by Dustan Kasten for browsers that don't support it yet. The native API doesn't support speed adjustment so neither will this component, there are however other react smooth scroll solutions out there that will do smooth scrolling with the option to adjust the speed.
