### ISSUE TITLE
focus is not being set

### ISSUE THREAD

**Issue by NSoiffer** [mauricevancooten/react-anchor-link-smooth-scroll#16]
The focus needs to be set in addition to scrolling to the target. This is important for accessibility and is the default behavior when `<a>` is used.

You can test this with the free NVDA screen reader (use down arrow after activating the link to hear where the focus is). I found [this project](https://github.com/jamesqquick/React-With-Smooth-Scrolling) was a simple way to do a test with NVDA.

**Comment by mauricevancooten** [comment]
Feel free to create a pull request with the fix for this.
