### ISSUE TITLE
Default behaviour for href with anchor

### ISSUE THREAD

**Issue by VladBlow** [mauricevancooten/react-anchor-link-smooth-scroll#17]
Hey, thanks for the good solution for smooth scroll. 

I found a small features which I want to be see in library. Default behaviour for href with anchor is add `#anchor` to route, but it is a missed.

What do you think about added props like `defaultPrevented` for component?

I can make a PR with this feature.

**Comment by tophsic** [comment]
Do you mean that you would like to see `#anchor` appear in route and browser history? This can be related to #14, isn't it?

**Comment by VladBlow** [comment]
@tophsic 
No, I talk about `#achor` in url.
For example: we have url like `http://localhost:4000` and we click in AnchorLink.
Url doesn't change because click have `e.prefentDefault();`
I want to see change url to `http://localhost:4000#anchor`, because this is important for me.

I think feature for disable/enable `preventDefault` behaviour is important.

**Comment by VladBlow** [comment]
I just coped and pasted code from library, because it's simple and trivial solution. 
But I think it's feature maybe useful for other people.

**Comment by tophsic** [comment]
> No, I talk about #anchor in url.
> For example: we have url like http://localhost:4000 and we click in AnchorLink.
> Url doesn't change because click have e.prefentDefault();
> I want to see change url to http://localhost:4000#anchor, because this is important for me.

My english seems too bad because that's what I meant ;) I am looking for the same thing so.

**Comment by tophsic** [comment]
Maybe I just was wrong to link the issue I mentioned.

**Comment by VladBlow** [comment]
@tophsic I just create PR soon :)

**Comment by mauricevancooten** [comment]
Feel free to submit a pull request with the feature and I will merge it into the repo!
