### ISSUE TITLE
How do I go to another page and an anchor within that other page within the same SPA using HashLink? page#subsection is not working, but it works perfectly with regular Link from react-router-dom

### ISSUE THREAD

**Issue by juanlet** [mauricevancooten/react-anchor-link-smooth-scroll#21]
Hey, I have section A and section B. Section A has all  AnchorLink components  to smoothly scroll to each section and that works fine, except for one of the links that goes to section B which is in another page. When I go to section B I still have the same navbar with the all the AnchorLinks that refers to subsections of section A. But if I use  href="page#subsection" doesn't work when using AnchorLink component. This works fine with regular Link component from react-router but I wanted to know if it was possible to do it with AnchorLink component and if possible keeping the smooth scroll behaviour when going to another section#subsection .  Otherwise I guess I'll have to render the navbar with either Link or AnchorLink depending on  in which route I'm in with the help of this.props.location.pathname.

**Comment by mauricevancooten** [comment]
I'm not sure, I haven't tried to do this before.

**Comment by MarcelWepper** [comment]
Is there any update on this topic? Did you use the alternative by rendering an other navbar?

**Comment by mwoz123** [comment]
I'd love to see such feature.
Guy's did you work around that?

**Comment by alainkaiser** [comment]
@juanlet Any news on this one? How did you solve it?

**Comment by Fauzdar1** [comment]
@mauricevancooten No updates since then? Any solution so far?

**Comment by sysotel** [comment]
+1

**Comment by Jxmedia** [comment]
Dam nothing on this? interested as well
