### ISSUE TITLE
Offset settings for different viewport

### ISSUE THREAD

**Issue by imshuffling** [mauricevancooten/react-anchor-link-smooth-scroll#4]
Would be cool if we could adjust the offset for different viewports.

e.g. 
`<AnchorLink offset='205' offset-sm='210' className="btn nav-item" href='#speakers'>Speakers</AnchorLink>
`

Thoughts?

**Comment by mauricevancooten** [comment]
I can see how that could be more dynamic. We'd also need to specify the breakpoints.

**Comment by DanMMX** [comment]
Maybe a function would be nicer, so anyone could adjust offset according to needs, something like

```
<AnchorLink offset={() => someCalc()} />
```
