### ISSUE TITLE
Hash doesn't change in the address bar

### ISSUE THREAD

**Issue by gazpachu** [mauricevancooten/react-anchor-link-smooth-scroll#5]
It might not be an issue, but I've noticed that, after changing my `a` tags to `AnchorLink`, the hash in the address bar doesn't change any more.

It could be fixed by adding an `onClick` event to the AnchorLinks and setting manually the hash, but I was wondering if we could add this feature to the module.

Thanks!

**Comment by gazpachu** [comment]
Correction: the `onClick` event in the `AnchorLink` doesn't work either

**Comment by gazpachu** [comment]
I.e. a top nav with links that when clicked scroll to the given section. After the animation ends, the address bar will get the hash of the section, in case the user decides to share a link to that page and section. Like in the wikipedia articles.

By theway, the onClick issuecan be

**Comment by mauricevancooten** [comment]
If you want to create a pull request with the fix I'll be happy to include it. Thanks for your enquiry.
