### ISSUE TITLE
Add Feature Responsive Offset

### ISSUE THREAD

**Issue by rohmanhm** [mauricevancooten/react-anchor-link-smooth-scroll#9]
I think it will be nice if you add support for responsive offset by window breakpoint.
For example: For the desktop breakpoint, the offset is 80 and when it comes to mobile breakpoint the offset changed to 10.

**Comment by DanMMX** [comment]
You can check my PR #8 and see if that works for you @rohmanhm

**Comment by mauricevancooten** [comment]
Thanks @DanMMX for your contribution.
